2023-05-19 14:32:10,590 INFO: Application [in /home/timo/Documents/Prototype/app/__init__.py:42]
2023-05-19 14:32:57,068 INFO: Application [in /home/timo/Documents/Prototype/app/__init__.py:42]
2023-05-19 14:48:03,880 INFO: Application [in /home/timo/Documents/Prototype/app/__init__.py:42]
2023-05-19 14:48:43,838 INFO: Application [in /home/timo/Documents/Prototype/app/__init__.py:42]
2023-05-19 14:50:26,732 INFO: Application [in /home/timo/Documents/Prototype/app/__init__.py:42]
2023-05-19 14:54:47,701 INFO: Application [in /home/timo/Documents/Prototype/app/__init__.py:42]
2023-05-19 14:56:40,525 INFO: Application [in /home/timo/Documents/Prototype/app/__init__.py:42]
2023-05-19 14:58:33,976 INFO: Application [in /home/timo/Documents/Prototype/app/__init__.py:42]
2023-05-19 15:07:13,602 INFO: Application [in /home/timo/Documents/Prototype/app/__init__.py:47]
2023-05-19 15:07:18,576 ERROR: Exception on /index [GET] [in /home/timo/miniconda3/envs/archpy_env/lib/python3.10/site-packages/flask/app.py:1744]
Traceback (most recent call last):
  File "/home/timo/miniconda3/envs/archpy_env/lib/python3.10/site-packages/flask/app.py", line 2528, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/timo/miniconda3/envs/archpy_env/lib/python3.10/site-packages/flask/app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/timo/miniconda3/envs/archpy_env/lib/python3.10/site-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/timo/miniconda3/envs/archpy_env/lib/python3.10/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/timo/Documents/Prototype/app/routes.py", line 35, in index
    return render_template('index.html', title='Home', submissions=submissions)
  File "/home/timo/miniconda3/envs/archpy_env/lib/python3.10/site-packages/flask/templating.py", line 147, in render_template
    return _render(app, template, context)
  File "/home/timo/miniconda3/envs/archpy_env/lib/python3.10/site-packages/flask/templating.py", line 130, in _render
    rv = template.render(context)
  File "/home/timo/.local/lib/python3.10/site-packages/jinja2/environment.py", line 1301, in render
    self.environment.handle_exception()
  File "/home/timo/.local/lib/python3.10/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/home/timo/Documents/Prototype/app/templates/index.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/home/timo/Documents/Prototype/app/templates/base.html", line 119, in top-level template code
    {% block content %}
  File "/home/timo/Documents/Prototype/app/templates/index.html", line 163, in block 'content'
    <li> {{ submission }} <a href="{{ url_for('view', id=submission.id) }}">view</a> <a href="{{ url_for('delete', id=submission.id) }}">delete</a></li>
  File "/home/timo/Documents/Prototype/app/models.py", line 79, in __repr__
    return '{}, {}, {}, {}'.format(self.name, moment(self.timestamp).format('LLL'), self.status, self.complete)
TypeError: 'Moment' object is not callable
2023-05-19 15:16:39,291 INFO: Application [in /home/timo/Documents/Prototype/app/__init__.py:47]
2023-05-19 15:18:31,359 INFO: Application [in /home/timo/Documents/Prototype/app/__init__.py:47]
2023-05-19 15:21:07,172 INFO: Application [in /home/timo/Documents/Prototype/app/__init__.py:47]
2023-05-19 15:21:08,800 ERROR: Exception on /submission [GET] [in /home/timo/miniconda3/envs/archpy_env/lib/python3.10/site-packages/flask/app.py:1744]
Traceback (most recent call last):
  File "/home/timo/miniconda3/envs/archpy_env/lib/python3.10/site-packages/flask/app.py", line 2528, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/timo/miniconda3/envs/archpy_env/lib/python3.10/site-packages/flask/app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/timo/miniconda3/envs/archpy_env/lib/python3.10/site-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/timo/miniconda3/envs/archpy_env/lib/python3.10/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/timo/miniconda3/envs/archpy_env/lib/python3.10/site-packages/flask_login/utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "/home/timo/Documents/Prototype/app/routes.py", line 36, in submission
    return render_template('submission.html', title='Home', submissions=submissions)
  File "/home/timo/miniconda3/envs/archpy_env/lib/python3.10/site-packages/flask/templating.py", line 147, in render_template
    return _render(app, template, context)
  File "/home/timo/miniconda3/envs/archpy_env/lib/python3.10/site-packages/flask/templating.py", line 130, in _render
    rv = template.render(context)
  File "/home/timo/.local/lib/python3.10/site-packages/jinja2/environment.py", line 1301, in render
    self.environment.handle_exception()
  File "/home/timo/.local/lib/python3.10/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/home/timo/Documents/Prototype/app/templates/submission.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/home/timo/Documents/Prototype/app/templates/base.html", line 119, in top-level template code
    {% block content %}
  File "/home/timo/Documents/Prototype/app/templates/submission.html", line 29, in block 'content'
    You can submit jobs <a href="{{ url_for('inedx') }}">here</a>.
  File "/home/timo/miniconda3/envs/archpy_env/lib/python3.10/site-packages/flask/app.py", line 2034, in url_for
    return self.handle_url_build_error(error, endpoint, values)
  File "/home/timo/miniconda3/envs/archpy_env/lib/python3.10/site-packages/flask/app.py", line 2023, in url_for
    rv = url_adapter.build(  # type: ignore[union-attr]
  File "/home/timo/miniconda3/envs/archpy_env/lib/python3.10/site-packages/werkzeug/routing/map.py", line 917, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.exceptions.BuildError: Could not build url for endpoint 'inedx'. Did you mean 'index' instead?
2023-05-19 15:21:39,356 INFO: Application [in /home/timo/Documents/Prototype/app/__init__.py:47]
2023-05-19 15:29:56,365 INFO: Application [in /home/timo/Documents/Prototype/app/__init__.py:47]
2023-05-19 15:30:33,896 INFO: Application [in /home/timo/Documents/Prototype/app/__init__.py:47]
2023-05-19 15:32:52,823 INFO: Application [in /home/timo/Documents/Prototype/app/__init__.py:47]
2023-05-19 15:38:02,956 INFO: Application [in /home/timo/Documents/Prototype/app/__init__.py:47]
2023-05-19 16:00:49,158 INFO: Application [in /home/timo/Documents/Prototype/app/__init__.py:47]
2023-05-19 16:01:23,595 INFO: Application [in /home/timo/Documents/Prototype/app/__init__.py:47]
2023-05-19 16:01:44,296 INFO: Application [in /home/timo/Documents/Prototype/app/__init__.py:47]
2023-05-19 16:03:07,511 INFO: Application [in /home/timo/Documents/Prototype/app/__init__.py:47]
2023-05-19 16:05:39,473 INFO: Application [in /home/timo/Documents/Prototype/app/__init__.py:47]
2023-05-19 16:07:38,407 INFO: Application [in /home/timo/Documents/Prototype/app/__init__.py:47]
2023-05-19 16:08:22,139 INFO: Application [in /home/timo/Documents/Prototype/app/__init__.py:47]
2023-05-25 14:51:55,331 INFO: Application [in /home/timo/Documents/Prototype/app/__init__.py:47]
2023-05-25 14:52:23,500 INFO: Application [in /home/timo/Documents/Prototype/app/__init__.py:47]
2023-05-25 14:52:30,538 INFO: Application [in /home/timo/Documents/Prototype/app/__init__.py:47]
2023-05-25 14:52:41,213 INFO: Application [in /home/timo/Documents/Prototype/app/__init__.py:47]
2023-05-25 14:53:22,362 INFO: Application [in /home/timo/Documents/Prototype/app/__init__.py:47]
2023-05-25 15:00:41,588 INFO: Application [in /home/timo/Documents/Prototype/app/__init__.py:47]
2023-05-25 15:02:09,374 INFO: Application [in /home/timo/Documents/Prototype/app/__init__.py:47]
2023-05-25 15:11:10,603 INFO: Application [in /home/timo/Documents/Prototype/app/__init__.py:47]
2023-05-25 15:18:10,232 INFO: Application [in /home/timo/Documents/Prototype/app/__init__.py:47]
