2023-05-04 15:40:24,603 INFO: Application [in /home/timo/Documents/Prototype/app/__init__.py:41]
2023-05-04 15:40:27,006 ERROR: Exception on /view [GET] [in /home/timo/miniconda3/envs/archpy_env/lib/python3.10/site-packages/flask/app.py:1744]
Traceback (most recent call last):
  File "/home/timo/miniconda3/envs/archpy_env/lib/python3.10/site-packages/flask/app.py", line 2528, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/timo/miniconda3/envs/archpy_env/lib/python3.10/site-packages/flask/app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/timo/miniconda3/envs/archpy_env/lib/python3.10/site-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/timo/miniconda3/envs/archpy_env/lib/python3.10/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/timo/miniconda3/envs/archpy_env/lib/python3.10/site-packages/flask_login/utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "/home/timo/Documents/Prototype/app/routes.py", line 172, in view
    return render_template('view2.html', plot=html)
  File "/home/timo/miniconda3/envs/archpy_env/lib/python3.10/site-packages/flask/templating.py", line 146, in render_template
    template = app.jinja_env.get_or_select_template(template_name_or_list)
  File "/home/timo/.local/lib/python3.10/site-packages/jinja2/environment.py", line 1081, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/home/timo/.local/lib/python3.10/site-packages/jinja2/environment.py", line 1010, in get_template
    return self._load_template(name, globals)
  File "/home/timo/.local/lib/python3.10/site-packages/jinja2/environment.py", line 969, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "/home/timo/.local/lib/python3.10/site-packages/jinja2/loaders.py", line 138, in load
    code = environment.compile(source, name, filename)
  File "/home/timo/.local/lib/python3.10/site-packages/jinja2/environment.py", line 768, in compile
    self.handle_exception(source=source_hint)
  File "/home/timo/.local/lib/python3.10/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/home/timo/Documents/Prototype/app/templates/view2.html", line 7, in template
    {% plot %}
jinja2.exceptions.TemplateSyntaxError: Encountered unknown tag 'plot'. Jinja was looking for the following tags: 'endblock'. The innermost block that needs to be closed is 'block'.
2023-05-04 15:41:42,499 INFO: Application [in /home/timo/Documents/Prototype/app/__init__.py:41]
2023-05-04 15:43:52,179 INFO: Application [in /home/timo/Documents/Prototype/app/__init__.py:41]
2023-05-04 15:45:40,251 INFO: Application [in /home/timo/Documents/Prototype/app/__init__.py:41]
2023-05-04 15:46:40,786 INFO: Application [in /home/timo/Documents/Prototype/app/__init__.py:41]
2023-05-04 15:48:56,629 INFO: Application [in /home/timo/Documents/Prototype/app/__init__.py:41]
2023-05-04 15:53:58,397 INFO: Application [in /home/timo/Documents/Prototype/app/__init__.py:42]
2023-05-04 15:54:16,984 INFO: Application [in /home/timo/Documents/Prototype/app/__init__.py:42]
2023-05-04 15:54:31,263 INFO: Application [in /home/timo/Documents/Prototype/app/__init__.py:42]
